DashcamConfig = {}

DashcamConfig.ToggleCommand = "toggledashcam"
DashcamConfig.SetDash = "setdash"

DashcamConfig.useMPH = true -- False will turn it to KMH
DashcamConfig.StateOfCam = "Phoenix Protocol"

DashcamConfig.RestrictVehicles = true
DashcamConfig.RestrictionType = "custom" -- custom / class

DashcamConfig.AllowedVehicles = {
"lcso19tahoe",
"lcso18f150",
"lcso20exp",
"lcso22taco",
"lcso21tahoe",
"lcso18chgr",
"lcso21chrhc",
"lcso21dura",
"lcso22exped",
"lcso22at4",
"esu19raptor",
"cidgranger",
"cid22trans",
"pb18Caracara", 
"pb14stanier",
"pb18buffalo",
"pb20scout", 
"pb21gresley", 
"justice1slick", 
"pb22granger", 
"justice4slick", 
"justice18slick", 
"justice10slick", 
"justice15", 
"justicegator", 
"justice8slick", 
"justice11slick", 
"v11vic",
"ls11cvpi",
"ls16FPIU",
"ls18char",
"ls18f150",
"ls21tahoe",
"ls18fpis",
"ls21dur",
"ls14tahoe",
"ls20FPIU",
"ls18tahoe",
"ls16rams",
"ls14char",
"11sahpcvpi",
"hp19intrcpt",
"16sahpfpiu",
"18sahpf150",
"20sahpfpiu",
"18sahpcharger",
"hp14buffalo",
"hp19gresley",
"19sahptahoes",
"hp24domntr",
"20sahpfpius",
"hp23granger",
"16sahpram",
"hp21sadler",
"k920scoutbb",
"k920sandking",
"23chak9a",
"k920granger",
"k9expa",
"k9gres",
"c3txdpscat",
"c3txdpscatb",
"camviprb",
"camvipbb",
"nikoltd",
"nikoltdbb",
"nxsmods06h1",
"nxsmods11vic",
"nxsmods20exp",
"nxsmods20mustang",
"nxsmods20tah",
"nxsmods21durango",
"nxsmods21sierra",
"nxsmods22expedition",
"nxsmods22tacoma",
"nxsmods22charger",
"nxsmodsbearcat",
"du18charger",
"victoria",
"18f150st"

}